# Generated by Django 2.2 on 2019-09-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0002_auto_20190902_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiFang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suifang_day', models.IntegerField(default=1, verbose_name='术后')),
                ('suifang_ft', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='腹痛')),
                ('suifang_fz', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='腹胀')),
                ('suifang_fr', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='发热')),
                ('suifang_ot', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='呕吐')),
                ('suifang_hy', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='黄疸')),
                ('suifang_dgy', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='急性胆管炎')),
                ('suifang_cyjs', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胆管残余结石')),
                ('suifang_yxy', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='急性胰腺炎')),
                ('suifang_dgxz', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胆管狭窄')),
                ('suifang_jz', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='是否就诊')),
                ('suifang_ffjs', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='复发结石')),
                ('suifang_dgzw', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胆管占位')),
                ('suifang_hos', models.CharField(blank=True, max_length=20, verbose_name='就诊医院')),
                ('suifang_tus_dzgzj', models.FloatField(default=0, verbose_name='胆总管最大直径')),
                ('suifang_tus_jszj', models.FloatField(default=0, verbose_name='残余结石直径')),
                ('suifang_tus_zdzj', models.FloatField(default=0, verbose_name='结石最大直径')),
                ('suifang_tus_jssm', models.IntegerField(default=0, verbose_name='复发结石数目')),
                ('suifang_tbil', models.FloatField(default=0, verbose_name='TBIL(mmol/L)')),
                ('suifang_dbil', models.FloatField(default=0, verbose_name='DBIL(mmol/L)')),
                ('suifang_alb', models.FloatField(default=0, verbose_name='ALB(g/L)')),
                ('suifang_ast', models.FloatField(default=0, verbose_name='AST(U/L)')),
                ('suifang_alt', models.FloatField(default=0, verbose_name='ALT(U/L)')),
                ('suifang_alp', models.FloatField(default=0, verbose_name='ALP(U/L)')),
                ('suifang_ggt', models.FloatField(default=0, verbose_name='GGT(U/L)')),
                ('suifang_mrcp', models.CharField(blank=True, max_length=50, verbose_name='MRCP')),
                ('suifang_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient', verbose_name='就诊号')),
            ],
            options={
                'verbose_name': '随访',
                'verbose_name_plural': '随访',
            },
        ),
    ]
