# Generated by Django 2.2 on 2019-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiFang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suifang',
            name='suifang_cyjs',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='胆管残余结石'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_dgxz',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='胆管狭窄'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_dgy',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='急性胆管炎'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_dgzw',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='胆管占位'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_ffjs',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='复发结石'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_fr',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='发热'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_ft',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='腹痛'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_fz',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='腹胀'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_hy',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='黄疸'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_jz',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='是否就诊'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_ot',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='呕吐'),
        ),
        migrations.AlterField(
            model_name='suifang',
            name='suifang_yxy',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], default='yes', max_length=10, verbose_name='急性胰腺炎'),
        ),
    ]
