# Generated by Django 2.2 on 2019-09-01 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_ft', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='腹痛')),
                ('after_fz', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='腹胀')),
                ('after_fr', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='发热')),
                ('after_ot', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='呕吐')),
                ('after_dl', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胆漏')),
                ('after_cx', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='术后出血')),
                ('after_cx_number', models.FloatField(default=0, verbose_name='')),
                ('after_yxy', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胰腺炎')),
                ('after_cs', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='残石')),
                ('after_other', models.CharField(blank=True, max_length=100, verbose_name='其他病发症')),
                ('after_pain', models.CharField(choices=[('0', '0: 无痛'), ('1', '1~3: 轻度疼痛'), ('2', '4~6: 中度疼痛'), ('3', '7~10: 重度疼痛')], max_length=20, verbose_name='疼痛评分')),
                ('after_satisfy', models.CharField(choices=[('0', '0: 不满意'), ('1', '1~3: 一般'), ('2', '4~6: 满意'), ('3', '7~10: 非常满意')], max_length=20, verbose_name='满意度评分')),
                ('after_out_date', models.DateField(default=datetime.date(2019, 9, 1), verbose_name='出院日期')),
                ('after_out_day', models.IntegerField(default=0, verbose_name='住院天数')),
                ('after_out_cost', models.FloatField(default=0, verbose_name='住院费用')),
                ('after_patient_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient', verbose_name='就诊号')),
            ],
            options={
                'verbose_name': '术后并发症',
                'verbose_name_plural': '术后并发症',
            },
        ),
    ]
