# Generated by Django 2.2 on 2019-09-02 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('After_op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afteroperate',
            name='after_out_date',
            field=models.DateField(default=datetime.date(2019, 9, 2), verbose_name='出院日期'),
        ),
    ]
