# Generated by Django 2.2 on 2019-09-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUS',
            fields=[
                ('eus_check_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='检查号')),
                ('eus_day', models.IntegerField(default=0, verbose_name='术前(天)')),
                ('eus_way', models.CharField(choices=[('hs', '环扫'), ('ss', '扇扫')], max_length=10, verbose_name='方式')),
                ('eus_dzgzj', models.IntegerField(default=0, verbose_name='胆总管直径')),
                ('eus_ygzj', models.IntegerField(default=0, verbose_name='胰管直径')),
                ('eus_blgb', models.CharField(choices=[('dzgjs', '胆总管结石'), ('dzgkz', '胆总管扩张'), ('dnjs', '胆囊结石'), ('dngjs', '胆囊管结石'), ('hlxz', '胆管远端合流部狭窄'), ('zwzs', '胆总管占位梗阻')], max_length=30, verbose_name='病理改变')),
                ('eus_patient_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient', verbose_name='就诊号')),
            ],
            options={
                'verbose_name': 'EUS',
                'verbose_name_plural': 'EUS',
            },
        ),
    ]
