# Generated by Django 2.2 on 2019-09-01 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='就诊号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=5, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('hos_number', models.CharField(max_length=20, verbose_name='住院号')),
                ('jizhang_number', models.CharField(max_length=20, verbose_name='记账号')),
                ('doctor', models.CharField(choices=[('zzh', '赵志宏'), ('cz', '陈震'), ('ln', '李宁')], max_length=20, verbose_name='术者')),
                ('inTime', models.DateField(default=datetime.date(2019, 9, 1), verbose_name='入院时间')),
                ('outTime', models.DateField(default=datetime.date(2019, 9, 1), verbose_name='出院时间')),
                ('jiguan', models.CharField(default='天津', max_length=20, verbose_name='籍贯')),
                ('BMI', models.CharField(default='100', max_length=20, verbose_name='BMI')),
                ('phone', models.CharField(default='1', max_length=20, verbose_name='联系电话')),
                ('livePlace', models.CharField(default='天津', max_length=100, verbose_name='居住地')),
                ('mail', models.CharField(default='1', max_length=20, verbose_name='邮箱')),
                ('mailPlace', models.CharField(default='1', max_length=20, verbose_name='邮编')),
                ('gaoxueya', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='高血压')),
                ('gxy_year', models.IntegerField(default=0, verbose_name='')),
                ('guanxinbing', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='冠心病')),
                ('gxb_year', models.IntegerField(default=0, verbose_name='')),
                ('gmzj', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='冠脉支架')),
                ('gmzj_year', models.IntegerField(default=0, verbose_name='')),
                ('tnb', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='糖尿病')),
                ('tnb_year', models.IntegerField(default=0, verbose_name='')),
                ('nk_other', models.TextField(max_length=100, verbose_name='其他')),
                ('jxdyy', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='急性胆源性胰腺炎')),
                ('jxdyy_value', models.CharField(choices=[('low', '轻'), ('high', '重')], max_length=20, verbose_name='')),
                ('jxdgy', models.CharField(choices=[('AC', 'AC'), ('AOC', 'AOC'), ('AOSC', 'AOSC')], max_length=20, verbose_name='急性胆管炎')),
                ('jxdny', models.CharField(choices=[('yes_jieshi', '有结石'), ('no_jieshi', '无结石')], max_length=20, verbose_name='急性胆囊炎')),
                ('wk_other', models.TextField(max_length=100, verbose_name='其他')),
                ('wk_sss', models.TextField(max_length=100, verbose_name='手术史')),
                ('smoke', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='抽烟')),
                ('smoke_year', models.IntegerField(default=0, verbose_name='')),
                ('drink', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='饮酒')),
                ('drink_year', models.IntegerField(default=0, verbose_name='')),
                ('breakfast', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='不吃早餐')),
                ('breakfast_year', models.IntegerField(default=0, verbose_name='')),
                ('likegzc', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='喜高脂餐')),
                ('likegzc_year', models.IntegerField(default=0, verbose_name='')),
                ('likess', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='喜素食')),
                ('likess_year', models.IntegerField(default=0, verbose_name='')),
                ('likexl', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='喜辛辣食物')),
                ('likexl_year', models.IntegerField(default=0, verbose_name='')),
                ('grxg_other', models.TextField(max_length=100, verbose_name='其他')),
                ('family_jieshi', models.CharField(choices=[('dannang', '胆囊'), ('gannei', '肝内'), ('ganwai', '肝外')], max_length=10, verbose_name='结石')),
                ('family_ddzl', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='胆道肿瘤')),
                ('family_tnb', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='糖尿病')),
                ('family_gxy', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='高血压')),
                ('family_gzxz', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='高脂血症')),
                ('sq_dgy', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='急性化脓性胆管炎')),
                ('sq_yxy', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='急性胆源性胰腺炎')),
                ('sq_jsqd', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='乳头部结石嵌顿')),
                ('sq_hd', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='梗阻性黄疸')),
                ('sq_dzgkz', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='胆总管扩张')),
                ('sq_dzgjs', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='胆总管结石')),
                ('sq_dny', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='急性胆囊炎')),
                ('sq_dnjs', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=20, verbose_name='胆囊结石')),
            ],
            options={
                'verbose_name': '患者信息',
                'verbose_name_plural': '患者信息',
            },
        ),
    ]
