# Generated by Django 2.2 on 2019-09-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='inTime',
            field=models.DateField(verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='outTime',
            field=models.DateField(verbose_name='出院时间'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='就诊号'),
        ),
    ]
