# Generated by Django 2.2 on 2019-09-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20190902_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='jxdyy_value',
            field=models.CharField(blank=True, choices=[('low', '轻'), ('high', '重')], max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
