# Generated by Django 2.2 on 2019-09-01 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCBDE',
            fields=[
                ('lcbde_check_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='检查号')),
                ('lcbde_date', models.DateField(default=datetime.date(2019, 9, 1), verbose_name='手术日期')),
                ('lcbde_time', models.FloatField(default=0, verbose_name='手术时间')),
                ('lcbde_dnyz', models.CharField(choices=[('small', '轻'), ('big', '重')], max_length=10, verbose_name='胆囊炎症')),
                ('lcbde_size', models.CharField(choices=[('normal', '正常'), ('big', '增大'), ('small', '萎缩')], max_length=10, verbose_name='胆囊大小')),
                ('lcbde_dngzj', models.FloatField(default=0, verbose_name='胆囊管直径')),
                ('lcbde_dzgzj', models.FloatField(default=0, verbose_name='胆总管直径')),
                ('lcbde_qc', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='胆囊切除')),
                ('lcbde_ddj', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='术中胆道镜')),
                ('lcbde_jdng', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='经胆囊管')),
                ('lcbde_jdng_qs', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='取石')),
                ('lcbde_jdng_number', models.IntegerField(default=0, verbose_name='胆管结石')),
                ('lcbde_jdng_zdzj', models.FloatField(default=0, verbose_name='最大直径')),
                ('lcbde_jdng_way', models.CharField(blank=True, choices=[('jf', '继发'), ('yf', '原发')], max_length=10, verbose_name='')),
                ('lcbde_jdzg', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='经胆总管')),
                ('lcbde_jdzg_qs', models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='取石')),
                ('lcbde_jdzg_number', models.IntegerField(default=0, verbose_name='胆管结石')),
                ('lcbde_jdzg_zdzj', models.FloatField(default=0, verbose_name='最大直径')),
                ('lcbde_jdzg_way', models.CharField(blank=True, choices=[('jf', '继发'), ('yf', '原发')], max_length=10, verbose_name='')),
                ('lcbde_ddzy', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='术中胆道造影')),
                ('lcbde_fzzj', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='顺行放置支架')),
                ('lcbde_fzzj_way', models.CharField(choices=[('dzw', '单猪尾(胰管型)'), ('zg', '直管(胆管型)')], max_length=20, verbose_name='')),
                ('lcbde_fzzj_number', models.FloatField(default=0, verbose_name='')),
                ('lcbde_tlsj', models.IntegerField(default=0, verbose_name='支架脱落时间')),
                ('lcbde_zjbfz', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='支架并发症')),
                ('lcbde_fhway', models.CharField(choices=[('jd', '间断'), ('lx', '连续')], max_length=10, verbose_name='缝合方式')),
                ('lcbde_fxway', models.CharField(choices=[('dq', '单桥'), ('pds', 'PDS-II')], max_length=10, verbose_name='缝线类型')),
                ('lcbde_fxtype', models.CharField(choices=[('3-0', '3-0'), ('4-0', '4-0'), ('5-0', '5-0')], max_length=10, verbose_name='缝线型号')),
                ('lcbde_cx', models.FloatField(default=0, verbose_name='术中出血')),
                ('lcbde_fqyl', models.CharField(choices=[('0', '无'), ('1', '1根'), ('2', '2根')], max_length=10, verbose_name='腹腔引流')),
                ('lcbde_ylglx', models.CharField(choices=[('0', 'S6'), ('1', 'M6'), ('2', '乳胶管'), ('3', '硅胶管')], max_length=10, verbose_name='引流管类型')),
                ('lcbde_zzkf', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='中转开腹')),
                ('lcbde_sslx', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='手术录像')),
                ('lcbde_other', models.TextField(blank=True, verbose_name='其他')),
                ('lcbde_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient', verbose_name='就诊号')),
            ],
            options={
                'verbose_name': 'LCBDE',
                'verbose_name_plural': 'LCBDE',
            },
        ),
    ]
