# Generated by Django 2.2 on 2019-09-02 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCBDE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcbde',
            name='lcbde_date',
            field=models.DateField(default=datetime.date(2019, 9, 2), verbose_name='手术日期'),
        ),
    ]
