# Generated by Django 2.2 on 2019-09-01 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERCP',
            fields=[
                ('ercp_check_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='检查号')),
                ('ercp_day', models.IntegerField(default=0, verbose_name='术前')),
                ('ercp_rtlx', models.CharField(choices=[('xbq', '小半球'), ('dbq', '大半球'), ('bp', '扁平'), ('rtx', '乳头型'), ('spgx', '沙皮狗型')], max_length=20, verbose_name='乳头类型')),
                ('ercp_kkxz', models.CharField(choices=[('hb', '花瓣'), ('kl', '颗粒'), ('lx', '裂隙'), ('dz', '点状')], max_length=10, verbose_name='乳头开口形状')),
                ('ercp_kkdx', models.CharField(choices=[('small', '< 4mm'), ('big', '>= 4mm')], max_length=10, verbose_name='乳头开口大小')),
                ('ercp_dzpc', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=10, verbose_name='胆汁自行排出情况')),
                ('ercp_dzxz', models.CharField(choices=[('ql', '清亮'), ('hz', '浑浊'), ('yj', '淤积'), ('gr', '感染')], max_length=20, verbose_name='胆汁形状')),
                ('ercp_zwqs1', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=10, verbose_name='乳头周围憩室')),
                ('ercp_zwqs2', models.CharField(blank=True, choices=[('multi', '多发'), ('single', '单发')], max_length=10, verbose_name='')),
                ('ercp_qsdx', models.CharField(choices=[('1', '1cm'), ('2', '2cm'), ('3', '3cm'), ('4', '4cm')], max_length=10, verbose_name='估计憩室大小')),
                ('ercp_qswz', models.CharField(choices=[('left', '乳头在憩室左侧'), ('right', '乳头在憩室右侧'), ('middle', '乳头在憩室中央')], max_length=30, verbose_name='憩室位置(解剖位)')),
                ('ercp_rtqs', models.CharField(choices=[('1', '乳头开口在憩室外、根部在憩室外'), ('2', '乳头开口在憩室外、根部在憩室内'), ('3', '乳头开口在憩室外、根部沿憩室边缘'), ('4', '乳头开口及根部均在憩室内')], max_length=20, verbose_name='乳头与憩室间关系')),
                ('ercp_chaguan', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='插管')),
                ('ercp_cgny', models.CharField(choices=[('difficult', '困难'), ('normal', '一般'), ('easy', '容易')], max_length=10, verbose_name='插管难易程度')),
                ('ercp_est', models.CharField(choices=[('small', '小切开(仅切开开口)'), ('middle', '中切开(切断部分Oddi括约肌)'), ('big', '大切开(切断Oddi括约肌)'), ('other', '柱状气囊扩张')], max_length=30, verbose_name='EST')),
                ('ercp_erbd', models.CharField(choices=[('dzw', '单猪尾(胰管支架)'), ('zg', '直管')], max_length=20, verbose_name='ERBD')),
                ('ercp_erbd_diameter', models.FloatField(default=0, verbose_name='直径')),
                ('ercp_enbd', models.CharField(choices=[('zw', '猪尾型'), ('gn', '肝内型管')], max_length=20, verbose_name='ENBD')),
                ('ercp_enbd_diameter', models.FloatField(default=0, verbose_name='直径')),
                ('ercp_diagnose', models.CharField(choices=[('multi', '胆总管多发结石'), ('single', '胆总管单发结石'), ('kz', '胆总管扩张、胆汁淤积'), ('ch', '十二指肠乳头炎、排空迟缓'), ('xz', '缩窄性乳头炎')], max_length=30, verbose_name='ERCP诊断')),
                ('ercp_date', models.DateField(default=datetime.date(2019, 9, 1), verbose_name='内镜时间')),
                ('ercp_time_hour', models.IntegerField(default=0, verbose_name='操作时间')),
                ('ercp_time_min', models.IntegerField(default=0, verbose_name='')),
                ('ercp_video', models.CharField(choices=[('yes', '有'), ('no', '无')], max_length=10, verbose_name='录像')),
                ('ercp_other', models.TextField(blank=True, verbose_name='其他备注')),
                ('ercp_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient', verbose_name='就诊号')),
            ],
            options={
                'verbose_name': 'ERCP',
                'verbose_name_plural': 'ERCP',
            },
        ),
    ]
